# Generated by Django 5.1.1 on 2024-09-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
