# Generated by Django 5.1.1 on 2024-09-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_likes_count_delete_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes_count',
            new_name='llikes',
        ),
    ]
