# Generated by Django 5.1.1 on 2024-09-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Comment',
            new_name='comments',
        ),
    ]
