# Generated by Django 5.1.1 on 2024-09-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_rename_comment_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
